local opt = vim.opt
opt.cursorline = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.expandtab = true
opt.cursorcolumn = true
opt.number = true
opt.relativenumber = true
opt.backup = false
opt.hlsearch = true
opt.scrolloff = 10
opt.smartcase = true
opt.smartindent = true
opt.softtabstop = 2
opt.wildmenu = true
opt.writebackup = false
opt.clipboard = 'unnamedplus'
opt.wrap = false
